import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Link href="/" passHref>
            Home
          </Link>

          <Link href="/events" passHref>
            Events
          </Link>

          <Link href="/about-us" passHref>
            About Us
          </Link>
        </nav>
      </header>

      <div>
        {data.map((event) => (
          <Link key={event.id} href={`/events/${event.id}`} passHref>
            <Image
              width={200}
              height={200}
              src={event.image}
              alt={event.title}
            />
            <h2>{event.title}</h2>
            <p>{event.description}</p>
          </Link>
        ))}
      </div>

      <footer className={styles.footer}>
        Copyright &copy; {1900 + new Date().getYear()}{" "}
        <a href="https://github.com/kihiuFrank">kihiuFrank</a> All Rights
        Reserved.
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
